import defaultTheme from 'tailwindcss/defaultTheme'
import forms from '@tailwindcss/forms'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        'label-sm': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
        'headline-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
        'headline-sm': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
        'headline-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
        'label-caps': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
        'body-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
        'body-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      spacing: {
        'section-gap': '24px',
        'chip-gap': '8px',
        'grid-gutter': '16px',
        'base': '8px',
        'container-padding': '32px',
      },
      colors: {
        background: '#f7f9fb',
        'on-secondary-container': '#54647a',
        error: '#ba1a1a',
        secondary: '#505f76',
        'surface-container-high': '#e6e8ea',
        'surface-dim': '#d8dadc',
        'error-container': '#ffdad6',
        'inverse-surface': '#2d3133',
        'tertiary-fixed': '#dae2fd',
        'on-secondary-fixed-variant': '#38485d',
        'secondary-fixed': '#d3e4fe',
        'on-surface': '#191c1e',
        'surface-container-highest': '#e0e3e5',
        'tertiary-container': '#656d84',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-tint': '#0053db',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#dbe1ff',
        'surface-container-low': '#f2f4f6',
        'primary-container': '#2563eb',
        'inverse-primary': '#b4c5ff',
        outline: '#737686',
        'inverse-on-surface': '#eff1f3',
        'on-primary-fixed': '#00174b',
        'on-surface-variant': '#434655',
        'on-tertiary-fixed-variant': '#3f465c',
        'on-secondary-fixed': '#0b1c30',
        'surface-variant': '#e0e3e5',
        primary: '#004ac6',
        'surface-container': '#eceef0',
        'secondary-container': '#d0e1fb',
        'on-background': '#191c1e',
        'tertiary-fixed-dim': '#bec6e0',
        'on-primary': '#ffffff',
        tertiary: '#4d556b',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9fb',
        'on-primary-container': '#eeefff',
        'primary-fixed-dim': '#b4c5ff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#131b2e',
        'on-tertiary-container': '#eef0ff',
        surface: '#f7f9fb',
        'outline-variant': '#c3c6d7',
        'on-secondary': '#ffffff',
        sis: {
          primary: 'var(--sis-primary, #1B3A6B)',
          accent: 'var(--sis-accent, #2F7EC7)',
          light: 'var(--sis-light, #4A9FD4)',
          panel: 'var(--sis-panel, #F4F7FA)',
          text: 'var(--sis-text, #1A2332)',
          muted: 'var(--sis-muted, #6B7C93)',
          border: 'var(--sis-border, #D1DCE8)',
        },
        dark: {
          bg: 'var(--dark-bg, #0a1120)',
          'bg-alt': 'var(--dark-bg-alt, #070d1a)',
          'bg-deep': 'var(--dark-bg-deep, #0b1326)',
          'bg-card': 'var(--dark-bg-card, #101b31)',
          text: 'var(--dark-text, #eaf1fb)',
          'text-muted': 'var(--dark-text-muted, #a8b3cf)',
          'text-dim': 'var(--dark-text-dim, #c8d4ec)',
          'accent-blue': 'var(--dark-accent-blue, #37b6ff)',
          'accent-teal': 'var(--dark-accent-teal, #5fe0c4)',
        },
      },
      boxShadow: {
        glow: '0 20px 60px rgba(27, 58, 107, 0.18)',
        sis: '0 25px 60px rgba(27, 58, 107, 0.12)',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        blink: {
          '50%': { opacity: '0.25' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.4s infinite ease',
        blink: 'blink 1s step-end infinite',
      },
    },
  },
  plugins: [forms],
}
