export default [
  { client: "Khalda Petroleum", sector: "Oil & Gas", location: "Marsa Matrouh, Egypt", summary: "Deployment of Well Head Wireless HART Transmitters integrated into SCADA for real-time field control and remote monitoring across multiple well sites.", tags: ["SCADA", "HART", "Wireless"], icon: "oil_barrel" },
  { client: "Saudi Aramco", sector: "Oil & Gas", location: "KSA", summary: "Well Heads Safety System Upgrades using SIEMENS S7-400H, PCS7, Schneider Electric Triconex, and Foxboro technologies to meet SIL-2 safety standards.", tags: ["Safety Systems", "SIL-2", "Siemens PCS7"], icon: "security" },
  { client: "Béjaïa RO Plant", sector: "Water & Waste Water", location: "Algeria", summary: "Full commissioning of PLC and SCADA systems with network cybersecurity hardening for a 50,000 m³/day Reverse Osmosis desalination facility.", tags: ["PLC", "SCADA", "Cybersecurity"], icon: "water_drop" },
  { client: "SWCC", sector: "Water & Waste Water", location: "KSA", summary: "Hardware commissioning, software logic validation, and field integration for large-scale desalination operations serving 1.2M residents.", tags: ["Hardware", "Commissioning", "DCS"], icon: "waves" },
  { client: "Qaliobia Waste Water", sector: "Water & Waste Water", location: "Egypt", summary: "Full 6-phase project spanning design, civil, electrical, instrumentation, automation, and startup for a regional waste water treatment plant.", tags: ["End-to-End", "Automation", "IIoT"], icon: "water_drop" },
  { client: "UNIHA Water Technology", sector: "Water & Waste Water", location: "Al Arish, Egypt", summary: "Full automation of a 5-stage RO water treatment process over an architectural Ethernet backbone, enabling remote diagnostics.", tags: ["Ethernet", "RO Automation"], icon: "hub" },
  { client: "Gas Cool & Emisal", sector: "Chemical Industries", location: "Fayoum, Egypt", summary: "Advanced automation solutions for process optimisation within chemical manufacturing plants, including a centralised SCADA fire alarm system.", tags: ["Process Control", "Fire Safety"], icon: "science" },
  { client: "Henkel", sector: "Food, Beverage & FMCG", location: "6th of October, Egypt", summary: "SCADA upgrade, process automation for chemical mixing, Siemens TIA thermal control, chemical dosing, and AR-assisted live system validation.", tags: ["SCADA Upgrade", "AR Validation", "TIA"], icon: "blender" },
  { client: "BariQ", sector: "Food, Beverage & FMCG", location: "Cairo, Egypt", summary: "Specialised automation with ODOO ERP integration and smart SCADA reporting for real-time granular process monitoring and traceability.", tags: ["ERP Integration", "Smart Reporting"], icon: "monitoring" },
  { client: "TAK Foods Factory", sector: "Food, Beverage & FMCG", location: "Menofia, Egypt", summary: "Standardised Siemens PLC platform, modern HMI dashboards, variable frequency drives, and complete electrical panel renewal for production lines.", tags: ["Siemens PLC", "VFD", "HMI"], icon: "factory" },
  { client: "Al Takamol Cement", sector: "Heavy Industries", location: "Sudan", summary: "Industrial automation and support services for large-scale cement manufacturing, including kiln control and conveyor belt management systems.", tags: ["Kiln Control", "PLC", "SCADA"], icon: "domain" },
  { client: "Greater Cairo Foundries (GCF)", sector: "Heavy Industries", location: "Sharqia, Egypt", summary: "New Siemens automation system, SCADA WinCC upgrade, and full power/control panel supply, assembly and startup for metal foundry operations.", tags: ["WinCC", "Power Panels", "Siemens"], icon: "precision_manufacturing" }
]
